name: Ceedling Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Ceedling
        run: gem install ceedling -v 1.1.4 --no-document

      - name: Run unit tests
        working-directory: pps_tpi/ceedling
        run: ceedling test:all
